name: ax3000t.yml
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build_ax3000t:
    runs-on: ubuntu-20.04
    steps:
      - name: setup env
        run: sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
      - name: clone source
        run: |
          wget https://downloads.immortalwrt.org/releases/23.05.4/targets/mediatek/filogic/immortalwrt-sdk-23.05.4-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -Jxvf immortalwrt-sdk-23.05.4-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          mv immortalwrt-sdk-23.05.4-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64 immortalwrt
      - name: build
        run: |
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make download -j$(nproc)
          make -j$(nproc)
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./bin/packages/**/*.ipk
