name: ax3000t.yml
on:
  schedule:
    - cron: '0 0 0 * *'
jobs:
  build ax3000t:
    runs-on: ubuntu-20.04
    steps:
      - name: setup env
        run: sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
      - name: clone source
        run: git clone -b openwrt-23.05 --single-branch --filter=blob:none https://github.com/immortalwrt/immortalwrt
      - name: build
        run: |
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make download -j$(nproc)
          make -j$(nproc)
      - name: Release
        uses: softprops/action-gh-release@v2