name: Build OpenWrt Firmware

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点运行

env:
  SDK_URL: "https://downloads.openwrt.org/releases/22.03.5/targets/rockchip/armv8/openwrt-sdk-22.03.5-rockchip-armv8_gcc-11.2.0_musl.Linux-x86_64.tar.xz"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download SDK
        run: |
          echo "Downloading SDK from $SDK_URL"
          wget "$SDK_URL"
          if [ $? -ne 0 ]; then
            echo "Failed to download SDK"
            exit 1
          fi
          SDK_FILE=$(basename "$SDK_URL")
          tar xf "$SDK_FILE"
          if [ $? -ne 0 ]; then
            echo "Failed to extract SDK"
            exit 1
          fi
          cd "$(basename "$SDK_FILE" .tar.xz)"
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la

      - name: Add custom repositories
        run: |
          echo "src-git ssrplus https://github.com/fw876/helloworld.git" >> feeds.conf.default
          echo "src-git homebox https://github.com/immortalwrt/luci.git" >> feeds.conf.default

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure build
        run: |
          cat > .config << EOF
          CONFIG_TARGET_rockchip=y
          CONFIG_TARGET_rockchip_armv8=y
          CONFIG_TARGET_rockchip_armv8_DEVICE_friendlyarm_nanopi-r4s=y
          CONFIG_PACKAGE_luci-app-ssr-plus=y
          CONFIG_PACKAGE_luci-app-homebox=y
          EOF

      - name: Build firmware
        run: |
          make -j$(nproc) V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            bin/targets/rockchip/armv8/*.img.gz
            bin/targets/rockchip/armv8/*.img

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v$(date +'%Y%m%d')
          release_name: Release $(date +'%Y-%m-%d')
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/targets/rockchip/armv8/*.img.gz
          asset_name: openwrt-r4s-$(date +'%Y%m%d').img.gz
          asset_content_type: application/octet-stream 
