name: rockchip
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build_ax3000t:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup env
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
      - name: clone source
        run: |
          git clone -b openwrt-23.05 --single-branch --filter=blob:none https://github.com/immortalwrt/immortalwrt
      - name: build
        run: |
          mv r4sconfig immortalwrt/.config
          cd immortalwrt
          sed -i '$a src-git smpackage https://github.com/kenzok8/small-package' feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
      - name: ssr-plus
        run: |
          make package/luci-app-ssr-plus/prepare
          make package/luci-app-ssr-plus/download
          make package/luci-app-ssr-plus/compile
      - name: Release
        uses: actions/upload-artifact@v4
        with:
          name: rockchip
          path: ./bin/packages/**/luci/*.ipk
